services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - shared:/shared
    command: -c "max_connections=100"

  sudachi:
    container_name: sudachi
    build:
      context: ./sudachi
      dockerfile: Dockerfile
    volumes:
      - shared:/shared

  sentence_creator:
    container_name: sentence_creator
    build:
      context: ./sentence_creator
      dockerfile: Dockerfile
    restart: no
    environment:
      - MHS_THREADS=${MHS_THREADS}
      - MHS_MAX_SLICE_SIZE=${MHS_MAX_SLICE_SIZE}

      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

      - PATH_KANJIDIC=${PATH_KANJIDIC}
      - PATH_JMDICT=${PATH_JMDICT}
      - PATH_SENTENCES=${PATH_SENTENCES}
      - PATH_SENTENCES_SUDACHI=${PATH_SENTENCES_SUDACHI}

      - OUTPUT_FOLDER=${OUTPUT_FOLDER}
    volumes:
      - ./resources:/resources
      - shared:/shared
    depends_on:
      postgres:
        condition: service_healthy
      sudachi:
        condition: service_completed_successfully
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          memory: 12G

volumes:
  shared:


